export enum Permission {
  // Job permissions
  CREATE_JOB = "CREATE_JOB",
  EDIT_JOB = "EDIT_JOB",
  DELETE_JOB = "DELETE_JOB",
  VIEW_JOB = "VIEW_JOB",

  // Application permissions
  APPLY_JOB = "APPLY_JOB",
  VIEW_APPLICATION = "VIEW_APPLICATION",
  MANAGE_APPLICATION_STATUS = "MANAGE_APPLICATION_STATUS",
  WITHDRAW_APPLICATION = "WITHDRAW_APPLICATION",

  // Resume permissions
  CREATE_RESUME = "CREATE_RESUME",
  EDIT_RESUME = "EDIT_RESUME",
  DELETE_RESUME = "DELETE_RESUME",
  VIEW_RESUME = "VIEW_RESUME",

  // Company permissions
  CREATE_COMPANY = "CREATE_COMPANY",
  EDIT_COMPANY = "EDIT_COMPANY",
  DELETE_COMPANY = "DELETE_COMPANY",
  VIEW_COMPANY = "VIEW_COMPANY",

  // Recruiter permissions
  MANAGE_RECRUITERS = "MANAGE_RECRUITERS",

  // Admin permissions
  MANAGE_USERS = "MANAGE_USERS",
  MANAGE_COMPANIES = "MANAGE_COMPANIES",
  VIEW_AUDIT_LOGS = "VIEW_AUDIT_LOGS",
  VIEW_ANALYTICS = "VIEW_ANALYTICS",
  BROADCAST_NOTIFICATION = "BROADCAST_NOTIFICATION",
}
