export const CANDIDATES_MESSAGES = {
  CANDIDATE_NOT_FOUND: "Candidate not found",
  CANDIDATE_CREATED: "Candidate created successfully",
  CANDIDATE_RETRIEVED: "Candidate retrieved successfully",
  CANDIDATES_RETRIEVED: "Candidates retrieved successfully",
  CANDIDATE_UPDATED: "Candidate updated successfully",
  CANDIDATE_DELETED: "Candidate soft-deleted successfully",
  CANDIDATE_RESTORED: "Candidate restored successfully",
  FORBIDDEN_MODIFICATION: "You do not have permission to manage this candidate",
  FORBIDDEN_ACCESS: "You do not have permission to perform this action",
  CROSS_COMPANY_ACCESS_FORBIDDEN:
    "Cross-company access to another company's candidate is not permitted",
  EMAIL_ALREADY_EXISTS: "A candidate with this email address already exists in your company",
  PHONE_ALREADY_EXISTS: "A candidate with this phone number already exists in your company",
  REQUIRED_CONTACT_INFO: "At least email or phone number is required to create a candidate",
  RECRUITER_NOT_FOUND: "Assigned recruiter not found",
  RECRUITER_ROLE_INVALID: "Assigned user must have the RECRUITER role",
  RECRUITER_COMPANY_MISMATCH: "Assigned recruiter must belong to the same company",
  INVALID_STATUS_TRANSITION: "Invalid candidate status transition",
  BLACKLISTED_TRANSITION_FORBIDDEN: "Blacklisted candidates require explicit administrator action",
  CANNOT_RESTORE_ACTIVE: "Candidate is already active",
  CANNOT_DELETE_DELETED: "Candidate is already soft-deleted",
  SKILL_NOT_FOUND: "Skill not found on candidate profile",
  SKILL_ALREADY_EXISTS: "This skill is already assigned to the candidate",
  SKILL_CATALOGUE_NOT_FOUND: "Skill does not exist in master catalogue",
  EDUCATION_NOT_FOUND: "Education record not found",
  EXPERIENCE_NOT_FOUND: "Experience record not found",
  DOCUMENT_NOT_FOUND: "Document record not found",
  NOTE_NOT_FOUND: "Note not found",
  TAG_NOT_FOUND: "Tag not found",
  NOTE_AUTHOR_MISMATCH: "You can only modify notes authored by yourself",
  ACTIVE_RESUME_REPLACED: "Previous active resume replaced successfully",
};

export const PAGINATION_DEFAULTS = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 100,
};
