export const JOBS_MESSAGES = {
  JOB_NOT_FOUND: "Job not found",
  JOB_CREATED: "Job created successfully in draft status",
  JOB_RETRIEVED: "Job retrieved successfully",
  JOBS_RETRIEVED: "Jobs retrieved successfully",
  JOB_UPDATED: "Job updated successfully",
  JOB_PUBLISHED: "Job published successfully",
  JOB_OPENED: "Job opened successfully",
  JOB_PAUSED: "Job paused successfully",
  JOB_REOPENED: "Job reopened successfully",
  JOB_CLOSED: "Job closed successfully",
  JOB_ARCHIVED: "Job archived successfully",
  JOB_RESTORED: "Job restored successfully",
  JOB_DELETED: "Job soft-deleted successfully",
  RECRUITERS_ASSIGNED: "Recruiters assigned successfully",
  RECRUITER_REMOVED: "Recruiter removed successfully",
  FORBIDDEN_MODIFICATION: "You do not have permission to manage this job",
  FORBIDDEN_ACCESS: "You do not have permission to perform this action",
  CROSS_COMPANY_ACCESS_FORBIDDEN: "Cross-company access to another company's job is not permitted",
  DEPARTMENT_NOT_FOUND: "Department not found",
  DEPARTMENT_COMPANY_MISMATCH: "Department does not belong to the job's company",
  DEPARTMENT_INACTIVE: "Cannot assign to an inactive department",
  DEPARTMENT_DELETED: "Cannot assign to a soft-deleted department",
  COMPANY_NOT_FOUND: "Company does not exist",
  RECRUITER_NOT_FOUND: "One or more recruiters not found",
  RECRUITER_COMPANY_MISMATCH: "Recruiter does not belong to your company",
  RECRUITER_ROLE_INVALID: "Assigned user must have the RECRUITER role",
  RECRUITER_ALREADY_ASSIGNED: "Recruiter is already assigned to this job",
  RECRUITER_NOT_ASSIGNED: "Recruiter is not assigned to this job",
  INVALID_LIFECYCLE_TRANSITION: "Invalid job status transition",
  PUBLISH_VALIDATION_FAILED: "Publishing requires Title, Description, Employment Type, Workplace Type, Department, Openings > 0, and at least one assigned recruiter",
  ARCHIVED_JOB_READONLY: "Archived jobs are read-only and cannot be modified",
  CLOSED_JOB_APPLICATIONS_REJECTED: "Closed jobs cannot accept new applications",
  CANNOT_RESTORE_ACTIVE: "Job is already active",
  CANNOT_DELETE_DELETED: "Job is already soft-deleted",
  SKILL_NOT_FOUND: "One or more skills not found",
};

export const PAGINATION_DEFAULTS = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 100,
};
